############# English navigation ##############
# main menu    
[[main]]
name = "About"
URL = "about"
weight = 2
  
[[main]]
name = "Documentation"
URL = "documentation"
weight = 3

[[main]]
name = "Contact"
URL = "contact"
weight = 5

[[main]]
weight = 6
name = "Other"
hasChildren = true

  [[main]]
  parent = "Other"
  name = "Pricing"
  URL = "pricing"

  
  [[main]]
  parent = "Other"
  name = "Team"
  URL = "team"

  [[main]]
  parent = "Other"
  name = "FAQ"
  URL = "faq"
  
  [[main]]
  parent = "Other"
  name = "Changelog"
  URL = "changelog"

#Footer menu
[[footer]]
name = "About us"
URL = "about"

[[footer]]
name = "Contact us"
URL = "contact"

[[footer]]
name = "Documentation"
URL = "documentation"

[[footer]]
name = "Privacy Policy"
URL = "privacy-policy"

[[footer]]
name = "Terms of Service"
URL = "tos"