#################### default parameters ################################
# favicon
favicon = "images/favicon.ico"
# logo
logo = "images/logo.svg"
# OpenGraph / Twitter Card metadata
description = "With Githaxs, you have a Continuous Integration platform up and running in minutes. No complicated setup, not a single line of code to write."
author = "Githaxs"
image = "images/logo.svg" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Santa Monica, CA 90405"
mobile = ""
email = "hello@githaxs.com"
# contact form action
contact_form_action = "https://formspree.io/hello@githaxs.com" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-142384782-1"
# main sections
mainSections = ["blog", "docs"]
# search
search = true
# custom script on header
custom_script= ""


# Preloader
[preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Get Started"
link = "/basic-startup/quick-start/"

# Subscription
[subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://githaxs.us10.list-manage.com/subscribe/post?u=4d340282d6b711826273da19f&amp;id=4d16d0ed36"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
map_marker_label = "Agico"
map_zoom = 17

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################

[[social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://twitter.com/githaxs"


[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/githaxs"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin-in" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/company/githaxs/"